"""Agregar campo imagen_url a la tabla eventos

Revision ID: a19e8400f907
Revises: ba1c7525fbb4
Create Date: 2024-07-10 16:24:29.548058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19e8400f907'
down_revision = 'ba1c7525fbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
